### ISSUE TITLE
Adding website URL to repo "About"

### ISSUE THREAD

**Issue by wohfab** [tollwerk/a11y-bookmarklets#4]
Could you add the [https://tollwerk.github.io/a11y-bookmarklets/](https://tollwerk.github.io/a11y-bookmarklets/) link to the repo's "About" section? This way, you have the website more accessible in the overview.

![Screenshot 2024-08-27 at 16 28 14](https://github.com/user-attachments/assets/1fa575eb-2d92-4fd5-ab54-7d56c398a957)

**Comment by jkphl** [comment]
Done, thanks! 😊
